#server:
#  port: 9191
#
#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: CARDSERVICE
#          uri: lb://CARDSERVICE
#          predicates:
#            - Path=/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/fallback
#        - id: HOMESERVICE
#          uri: lb://HOMESERVICE
#          predicates:
#            - Path=/home/**
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
